[package]
name = "lichendle"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.10.0-rc.5"
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
libsql = "0.9.28"
regex = "1.12.2"
