name: Playwright Tests

on: pull_request

jobs:
  build-and-test:
    strategy:
      matrix:
        BUILD_TARGET: [ release ]
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v5

      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}

      - name: Generate html in "${{ matrix.BUILD_TARGET }}" mode
        run: CARGO_INCREMENTAL="0" DEV_MODE="1" MAX_ID="1" RUST_MIN_STACK="33554432" DATABASE_URL="/ui-tests/test.db" cargo run --profile ${{ matrix.BUILD_TARGET }}

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: ls
      - name: Install dependencies
        working-directory: ./ui-tests
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./ui-tests
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: 'file:html/index.html'
        working-directory: ./ui-tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
